[project]
name = "blazepose-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
]
